version: "3.8"


# For developement purposes I am not using vloumes and custom networks (using default driver instead)
services:

  email-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    image: email-service:latest
    container_name: email-service
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy

  alert-service:
    build:
      context: ./alert-service
      dockerfile: Dockerfile
    image: alert-service:latest
    container_name: alert-service
    ports:
      - 3000:3000
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    healthcheck:
      test: /opt/bitnami/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9092
      interval: 20s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crypto-alert
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3