// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"time"
)

type Alert struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Crypto    string    `json:"crypto"`
	Price     float64   `json:"price"`
	Direction bool      `json:"direction"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID             int64     `json:"id"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
}
