// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"context"
)

type Querier interface {
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAlertByID(ctx context.Context, id int64) (Alert, error)
	GetAlertsByStatus(ctx context.Context, arg GetAlertsByStatusParams) ([]Alert, error)
	GetAllAlerts(ctx context.Context, arg GetAllAlertsParams) ([]Alert, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	UpdateAlert(ctx context.Context, arg UpdateAlertParams) (Alert, error)
	UpdateAlertStatus(ctx context.Context, arg UpdateAlertStatusParams) error
}

var _ Querier = (*Queries)(nil)
