// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"context"
)

type Querier interface {
	GetUserEmailByAlertID(ctx context.Context, id int64) (string, error)
	UpdateAlertStatus(ctx context.Context, arg UpdateAlertStatusParams) error
}

var _ Querier = (*Queries)(nil)
