// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: users.sql

package database

import (
	"context"
)

const getUserEmailByAlertID = `-- name: GetUserEmailByAlertID :one
SELECT u.email
FROM "Users" u
INNER JOIN "Alerts" a ON u.id = a.user_id
WHERE a.id = $1
`

func (q *Queries) GetUserEmailByAlertID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getUserEmailByAlertID, id)
	var email string
	err := row.Scan(&email)
	return email, err
}
